version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/data/traefik.yml:/traefik.yml:ro
      - ./traefik/data/acme.json:/acme.json
      - ./traefik/data/config.yml:/config.yml:ro
    networks:
      - AgileNet
    labels:
      - "traefik.enable=true"

  redis:
    image: redis:7.2
    container_name: finance-redis
    restart: unless-stopped
    volumes:
      - ./redis-secure-config.conf:/usr/local/etc/redis/redis.conf
      - ./redis-logs:/var/log/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - AgileNet
    ports:
      - "6379:6379"

  api:
    image: node:18
    container_name: finance-api
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=0
    networks:
      - AgileNet
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`dev.agilefinance.com.br`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

networks:
  AgileNet:
    external: true
