openapi: 3.0.0
paths:
  /tasks:
    get:
      tags:
        - Tasks
      summary: Lista todas as tasks
      description: Retorna uma lista paginada de tasks com suporte a filtros
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Número da página
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Itens por página
        - in: query
          name: status
          schema:
            type: string
            enum: [pending, running, completed, failed]
          description: Filtrar por status da task
        - in: query
          name: type
          schema:
            type: string
          description: Filtrar por tipo de task
      responses:
        '200':
          description: Lista de tasks retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Tasks
      summary: Cria uma nova task
      description: Cria uma nova task no sistema
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - name
                - payload
              properties:
                type:
                  type: string
                  description: Tipo da task
                name:
                  type: string
                  description: Nome da task
                description:
                  type: string
                  description: Descrição da task
                payload:
                  type: object
                  description: Dados específicos da task
                priority:
                  type: integer
                  description: Prioridade da task (0-10)
                  default: 0
                metadata:
                  type: object
                  description: Metadados adicionais
      responses:
        '201':
          description: Task criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}:
    get:
      tags:
        - Tasks
      summary: Busca uma task por ID
      description: Retorna os detalhes de uma task específica
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da task
      responses:
        '200':
          description: Task encontrada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Tasks
      summary: Atualiza uma task
      description: Atualiza os dados de uma task existente
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, running, completed, failed]
                name:
                  type: string
                description:
                  type: string
                priority:
                  type: integer
                payload:
                  type: object
                metadata:
                  type: object
      responses:
        '200':
          description: Task atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Tasks
      summary: Remove uma task
      description: Remove uma task do sistema
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da task
      responses:
        '204':
          description: Task removida com sucesso
        '404':
          description: Task não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}/process:
    post:
      tags:
        - Tasks
      summary: Processa uma task
      description: Força o processamento imediato de uma task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da task
      responses:
        '200':
          description: Task processada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/logs:
    get:
      tags:
        - Tasks
      summary: Lista logs de tasks
      description: Retorna uma lista paginada de logs de execução das tasks
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: taskId
          schema:
            type: integer
          description: Filtrar por ID da task
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Número da página
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Itens por página
      responses:
        '200':
          description: Lista de logs retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TaskLog'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer

components:
  schemas:
    Task:
      type: object
      properties:
        task_id:
          type: integer
        type_id:
          type: integer
        status:
          type: string
          enum: [pending, running, completed, failed]
        priority:
          type: integer
        payload:
          type: object
        resource_id:
          type: string
        scheduled_for:
          type: string
          format: date-time
        started_at:
          type: string
          format: date-time
        finished_at:
          type: string
          format: date-time
        retry_count:
          type: integer
        next_retry_at:
          type: string
          format: date-time
        error_message:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        name:
          type: string
        description:
          type: string
        max_retries:
          type: integer
        retries:
          type: integer
        type_name:
          type: string
        type_description:
          type: string
        dependencies:
          type: array
          items:
            type: integer

    TaskLog:
      type: object
      properties:
        id:
          type: integer
        task_id:
          type: integer
        status:
          type: string
        message:
          type: string
        details:
          type: object
        created_at:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
