global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'finance-api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['finance-api:3000']
    basic_auth:
      username: 'prometheus'
      password: 'prometheus_secret'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
