paths:
  /addresses:
    get:
      summary: Listar endereços
      tags:
        - Addresses
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Número da página
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Quantidade de registros por página
        - in: query
          name: person_id
          schema:
            type: integer
          description: Filtrar por ID da pessoa
        - in: query
          name: city
          schema:
            type: string
          description: Filtrar por cidade
        - in: query
          name: state
          schema:
            type: string
          description: Filtrar por estado
      responses:
        '200':
          description: Lista de endereços
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Address'
                  total:
                    type: integer
                    description: Total de registros

    post:
      summary: Criar endereço
      tags:
        - Addresses
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAddress'
      responses:
        '201':
          description: Endereço criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'

  /addresses/{id}:
    get:
      summary: Buscar endereço por ID
      tags:
        - Addresses
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes do endereço
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
    put:
      summary: Atualizar endereço
      tags:
        - Addresses
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAddress'
      responses:
        '200':
          description: Endereço atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
    delete:
      summary: Deletar endereço
      tags:
        - Addresses
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Endereço deletado

  /addresses/person/{personId}:
    get:
      summary: Listar endereços de uma pessoa
      tags:
        - Addresses
      parameters:
        - in: path
          name: personId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de endereços da pessoa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Address'

  /addresses/cep/{cep}:
    get:
      summary: Buscar endereço por CEP
      tags:
        - Addresses
      parameters:
        - in: path
          name: cep
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes do endereço pelo CEP
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'

components:
  schemas:
    Address:
      type: object
      properties:
        id:
          type: integer
        person_id:
          type: integer
        street:
          type: string
        number:
          type: string
        complement:
          type: string
        neighborhood:
          type: string
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
        reference:
          type: string
        ibge:
          type: string
        is_main:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateAddress:
      type: object
      required:
        - person_id
        - street
        - number
        - neighborhood
        - city
        - state
        - postal_code
        - country
      properties:
        person_id:
          type: integer
        street:
          type: string
        number:
          type: string
        complement:
          type: string
        neighborhood:
          type: string
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
        reference:
          type: string
        ibge:
          type: string
        is_main:
          type: boolean
          default: false

    UpdateAddress:
      type: object
      properties:
        street:
          type: string
        number:
          type: string
        complement:
          type: string
        neighborhood:
          type: string
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
        reference:
          type: string
        ibge:
          type: string
        is_main:
          type: boolean
